DataModeling :
    SupervisedLearning :
        Convex :
        DecisionTree : False
        LinearRegression : 
        LogisticRegression : 
        MultinomialLogisticRegression : False
        NaiveBayesClassification : False
        RandomForest : False
        SupportVectorMachines : False
        GeneralCV : 
    UnsupervisedLearning : 
        kMeansClustering : False
        AssociationRules : False
        ParallelLatentDirichletAllocation : False
InferentialStatistics :
    HypothesisTests : False
Common :
