DataModeling :
    SupervisedLearning :
        Convex : false
        DecisionTree : false
        LinearRegression : false
        LogisticRegression : false
        MultinomialLogisticRegression : false
        NaiveBayesClassification : false
        RandomForest : false
        SupportVectorMachines : false
        GeneralCV : false
    UnsupervisedLearning :
        kMeansClustering : false
        AssociationRules : false
        ParallelLatentDirichletAllocation : false
        LDA :
InferentialStatistics :
    HypothesisTests : false
Common :

