DataModeling :
    SupervisedLearning :
        Convex : 
        DecisionTree : 
        LinearRegression : 
        LogisticRegression : 
        MultinomialLogisticRegression : 
        NaiveBayesClassification : 
        RandomForest : 
        SupportVectorMachines : 
        GeneralCV : 
    UnsupervisedLearning :
        kMeansClustering : 
        AssociationRules : 
        LDA :
InferentialStatistics :
    HypothesisTests : 
Common :

